server:
  port: 10080
  max-http-header-size: 102400

aml:
  swagger-open: true                #是否开启swagger (true/false)
  kaptcha-open: false               #是否开启登录时验证码 (true/false)
  spring-session-open: false        #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900  #多久检测一次失效的session(只在单机环境下生效) 单位：秒
  app-version: home                   #应用版本  bigData 大数据版本 / home 单机版
  appType:  pay                      #  bank 银行版 / pay 支付版
beetl:
  resource-auto-check: true         #热加载beetl模板，开发时候用

spring:
  profiles:
    active: local
  mvc:
    view:
      prefix: /pages
  devtools:
    restart:
      enabled: false
      additional-paths: src/main/java
      exclude: assets/**,pages/**
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB

mybatis-plus:
  typeAliasesPackage: com.ylink.aml.modular.system.model
  configuration:
    call-setters-on-nulls: true
log:
  path: guns-logs


